using CommandLine;
using SqlScriptMerge.Lib.Options;

namespace SqlScriptMerge.ConsoleApp
{
    internal class Options : IOptions
    {

        [Option('o', "SortOutputFileName", HelpText = "Output file name for sort mode")]
        public string? SortOutputFileName { get; set; }

        [Option("MergeOutputFileName", HelpText = "Output file name for merge mode")]
        public string? MergeOutputFileName { get; set; }

        [Option("InDirectory", HelpText = "Directory in which the input files are located. If no directory specified, program uses the working directory.")]
        public string? InDirectory { get; set; }

        [Option("FileExtension", HelpText = "File extension that is used to filter input files from directory (i.e. .sql). If no extension, the program takes all files from input directory.")]
        public string? FileExtension { get; set; }

        [Option('s', "SortMode", HelpText = "Only sorts the queries without trying to merge them.")]
        public bool SortMode { get; set; }

        [Option('m', "MergeMode", HelpText = "Mode which tries to reduce queries into one create query.")]
        public bool MergeMode { get; set; }

        [Option("NoMergeComments", HelpText = "Does not insert any autogenerated comments.")]
        public bool NoMergeComments { get; set; }

        [Option("NoAuthorComments", HelpText = "Ignores the comments.")]
        public bool NoAuthorComments { get; set; }


        [Option("CustomSpLoad", HelpText = "Option helping load files - designed for user JK")]
        public bool CustomSpLoad { get; set; }


    }
}