using CommandLine;
using SqlScriptMerge.Lib.Options;

namespace spOne.Desktop.Commons.Styling.XamlDictionaryMergeTool;

internal  class Options : IOptions
{

    [Option('o', "Output", HelpText = "Output file name")]
    public string? OutputFileName { get; set; }

    [Option('p', "AutoReadPrefix", HelpText = "Prefix that is used to automaticaly read files from current directory.")]
    public string? AutoReadPrefix { get; set; }

    [Option('s', "SortOnly", HelpText ="Only sorts the queries without trying to merge them.")]
    public bool OnlySort { get; set; }

    [Option('n', "NoComments", HelpText = "Does not insert any autogenerated comments.")]
    public bool NoComments { get; set; }

    [Option("NoSortOutput", HelpText = "Do not create sorted file.")]
    public bool NoSortOutput { get; set; }

    [Option("CustomSp", HelpText = "Custom setup ment for JK")]
    public bool CustomSp { get; set;}


}
